spring:
  datasource:
    url: jdbc:postgresql://localhost:9876/dev_db
    username: dev_user
    password: dev_pass
  cache:
    redis:
      time-to-live: PT1M
  data:
    redis:
      host: localhost
      port: 6370
      password: dev_cache_pass

